### ISSUE TITLE
compatible with Hogfather?

### ISSUE THREAD

**Issue by asheenlevrai** [gkrid/dokuwiki-plugin-dtable#13]
Hi :)

I am currently running Greebo and considering upgrading to Hogfather.
Is this plugin compatible with Hogfather?

Thanks
-a-

**Comment by solewniczak** [comment]
I've did some minor maintenance and the plugin should now work on Hogfather as well. But since the plugin is not very actively developed right now, please consider the struct plugin or edittable plugin as replacements.

**Comment by asheenlevrai** [comment]
Thanks for your reply.

I am sorry to learn that dtable is no longer actively developed (for now?). The ability to edit tables via a simple right-click is super convenient to me and the other users of our wiki. 

We have already tested the EditTable plugin in the past but it was way less convenient than dtable and less intuitive as well.

I don't understand how to struct plugin could be an alternative to dtable. AFAIU it serves a completely different purpose.

I hope this situation is only temporary and that you (or others) will regain interest in actively maintaining the great piece of work that dtable is.

Once again, **thank you** and **congratulations** for this plugin. It helps me and others a whole lot, on a daily basis.

Best,
-a-

**Comment by solewniczak** [comment]
It's not very actively developed right now but it doesn't mean that its abandoned :) I still use this plugin in my wikis and it works well. I hope that I'll find some time in a future to do a refactoring and make the plugin more robust.

**Comment by asheenlevrai** [comment]
This is great news!!!
awesome :)
